
services:
  seamless-upgrade-mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - seamless-upgrade-mongodb-data:/data/db

  backend:
    image: hyperflex/elastic-seamless-upgrade-backend:dev
    container_name: backend
    pull_policy: always
    environment:
      MONGO_URI: mongodb://admin:admin123@seamless-upgrade-mongodb:27017/
    depends_on:
      - seamless-upgrade-mongodb
    ports:
      - '3000:3000'

  seamless-upgrade-tool:
    image: hyperflex/elastic-seamless-upgrade-tool:dev
    container_name: tool
    pull_policy: always
    ports:
      - '8080:8080'
    depends_on:
      - backend

volumes:
  seamless-upgrade-mongodb-data:
