
services:
  seamless-upgrade-mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - seamless-upgrade-mongodb-data:/data/db

  seamless-upgrade-tool:
    image: hyperflex/elastic-seamless-upgrade-tool:dev
    container_name: tool
    pull_policy: always
    ports:
      - '8080:8080'
    volumes:
      - seamless-upgrade-tool:/output
    depends_on:
      - seamless-upgrade-mongodb

volumes:
  seamless-upgrade-tool:
  seamless-upgrade-mongodb-data:
