spring:
  main:
    banner-mode: "off"
  output:
    ansi-enabled: "never"
  application:
    name: Elastic Seamless Upgrade Tool
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/admin
      database: seamless-upgrade
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
      enabled: true
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=100,maximumSize=500,expireAfterAccess=5m

springdoc:
  swagger-ui:
    path: /swagger-ui.html

seamless:
  output:
    dir: "output"

# enable/disable https
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,application/json
    min-response-size: 1024