spring:
  application:
    name: NextGen Seamless Upgrade
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/admin
      database: seamless-upgrade
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
      enabled: true
app:
  ansible:
    playbooks-directory: /

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  health:
    elasticsearch:
      enabled: false

seamless:
  output:
    dir: "output"