spring:
  application:
    name: NextGen Seamless Upgrade
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/admin
      database: seamless-upgrade
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
      enabled: true
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=100,maximumSize=500,expireAfterAccess=5m

app:
  ansible:
    playbooks-directory: /

springdoc:
  swagger-ui:
    path: /swagger-ui.html

seamless:
  encryption-key: changeit
  output:
    dir: "output"

# enable/disable https
server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: ${SEAMLESS_UPGRADE_TOOL_TLS_KEY_STORE:classpath:keystore/keystore.p12}
    key-store-password: ${SEAMLESS_UPGRADE_TOOL_TLS_KEY_STORE_PASSWORD:changeit}
    key-alias: ${SEAMLESS_UPGRADE_TOOL_TLS_KEY_ALIAS:hyperflex}
    protocol: TLS
    enabled-protocols: TLSv1.2
