- hosts: all
  any_errors_fatal: true
  gather_facts: true
  vars:
      precheck_id: elasticsearch_cluster_health_check

  tasks:
      - name: Check Elasticsearch cluster health
        uri:
            url: "{{ elasticsearch_uri }}/_cluster/health?pretty"
            url_username: "{{ es_username }}"
            url_password: "{{ es_password }}"
            validate_certs: false
            method: GET
        register: cluster_health
        ignore_errors: yes

      - name: Display cluster health
        debug:
            msg: "Cluster is in {{ cluster_health.json.status }}"
        run_once: true

      - name: Cluster health is not green
        fail:
            msg: "Cluster is in {{ cluster_health.json.status }}, upgrade not recommended!"
        when: cluster_health.json.status != "green"
