- hosts: all
  become: true
  any_errors_fatal: true
  gather_facts: no
  vars:
      precheck_id: elasticsearch_disk_precheck
      DISK_SPACE_LIMIT: 75
  tasks:
      - name: Get disk space usage
        shell: df -h / | tail -n 1 | awk '{ print $5 }' | tr -d \%
        register: disk_usage
        changed_when: false

      - name: Show disk usage
        debug:
            msg: "Disk Usage: {{ disk_usage.stdout }}%"

      - name: Validating Node Disk utilization
        assert:
            that:
                - ( disk_usage.stdout | int ) < ( DISK_SPACE_LIMIT | int )
            fail_msg: "Disk Space Utilization is more than {{ DISK_SPACE_LIMIT }}"
            success_msg: "Disk Space is less than {{ DISK_SPACE_LIMIT }}"
