- hosts: all
  any_errors_fatal: true
  gather_facts: true
  vars:
      precheck_id: kibana_version_check
      kibana_host_protocol: "http"
      kibana_port: 5601

  tasks:
      - name: Get current Kibana version
        uri:
            url: "{{ kibana_host_protocol }}://localhost:{{ kibana_port }}/api/status"
            method: GET
            url_username: "{{ es_username }}"
            url_password: "{{ es_password }}"
            headers:
                kbn-xsrf: "true"
            validate_certs: false
        register: kibana_response
        retries: 10
        delay: 10
        until: kibana_response.status == 200

      - name: Display Current Kibana Version
        debug:
            msg: >-
                Precheck [{{ precheck_id }}] - Kibana version: {{ kibana_response.json.version.number }}
                on host: {{ inventory_hostname }}

      - name: Fail if Kibana version does not match the expected version
        fail:
            msg: >-
                Precheck [{{ precheck_id }}] failed on host {{ inventory_hostname }}. 
                Expected: {{ current_version }}, Found: {{ kibana_response.json.version.number }}
        when: kibana_response.json.version.number != current_version
