- hosts: all
  become: true
  any_errors_fatal: true
  gather_facts: no
  vars:
      precheck_id: elasticsearch_memory_precheck
      Memory_LIMIT: 80
  tasks:
      - name: Get memory usage
        shell: "free | grep '^Mem:' | awk '{mem_usage=($3*100)/$2} END {print mem_usage }'"
        register: memory_utilization

      - name: Show memory usage
        debug:
            msg: "Memory Usage: {{ memory_utilization.stdout }}%"
      - name: Validating Host Memory
        assert:
            that:
                - ( memory_utilization.stdout | int )  < Memory_LIMIT
            fail_msg: "Memory Utilization is more than  {{ Memory_LIMIT }}"
            success_msg: "Memory Utilization is less than  {{ Memory_LIMIT }}"
        register: MEMORY_CHECK_RESULT
        ignore_errors: yes
