---
- name: Elastic and Kibana package download
  import_playbook: pre-download-check.yml

- name: Elasticsearch data node upgrade
  import_playbook: elasticsearch-upgrade.yml
  vars:
    elasticsearch_node: elasticsearch_data

- name: Elasticsearch master node upgrade
  import_playbook: elasticsearch-upgrade.yml
  vars:
    elasticsearch_node: elasticsearch_master

- name: Kibana upgrade
  import_playbook: kibana-upgrade.yml