name: Build and Push Node18Ansible Docker Image

on:
    push:
        branches:
            - main
        paths:
            - "dockers/Dockerfile.node18-ansible" # Only run when this file changes

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: dockers/Dockerfile.node18-ansible
                  push: true
                  tags: hyperflex/node18ansible:latest
