name: Build Elastic Seamless Upgrade Tool
run-name: build-elastic-seamless-upgrade-tool

permissions:
  contents: read
  checks: write
  id-token: write

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set Docker tag
        id: set-tag
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "tag=dev" >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.event_name }}" == "create" && "${{ github.event.ref_type }}" == "tag" ]]; then
            echo "tag=${{ github.event.ref }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=latest" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push frontend image
        run: |
          docker build -t hyperflex/elastic-seamless-upgrade-frontend:${{ steps.set-tag.outputs.tag }} ./frontend
          docker push hyperflex/elastic-seamless-upgrade-frontend:${{ steps.set-tag.outputs.tag }}

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set Docker tag
        id: set-tag
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "tag=dev" >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.event_name }}" == "create" && "${{ github.event.ref_type }}" == "tag" ]]; then
            echo "tag=${{ github.event.ref }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=latest" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push backend image
        run: |
          docker build -t hyperflex/elastic-seamless-upgrade-backend:${{ steps.set-tag.outputs.tag }} ./backend
          docker push hyperflex/elastic-seamless-upgrade-backend:${{ steps.set-tag.outputs.tag }}

  test-tool:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # Or 'zulu', 'oracle', etc.
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Comment JUnit test summary on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'server/build/test-results/test/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          include_passed: 'true'

  build-tool:
    runs-on: ubuntu-latest
    needs:
      - test-tool
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set Docker tag
        id: set-tag
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "tag=dev" >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.event_name }}" == "create" && "${{ github.event.ref_type }}" == "tag" ]]; then
            echo "tag=${{ github.event.ref }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=latest" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push backend image
        run: |
          docker build -t hyperflex/elastic-seamless-upgrade-tool:${{ steps.set-tag.outputs.tag }} .
          docker push hyperflex/elastic-seamless-upgrade-tool:${{ steps.set-tag.outputs.tag }}
