name: Build Elastic Seamless Upgrade Tool
run-name: build-elastic-seamless-upgrade-tool

on:
  push:
    branches:
      - main
      - develop
    tags:
      - v*
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set Docker tag
        id: set-tag
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "tag=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
          elif [[ "${GITHUB_REF_NAME}" == "refs/heads/main" || "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "tag=latest" >> "$GITHUB_OUTPUT"
          else
            echo "tag=dev" >> "$GITHUB_OUTPUT"
          fi

      # Enable multi-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend   # or `.` for backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: hyperflex/elastic-seamless-upgrade-frontend:${{ steps.set-tag.outputs.tag }}

  test-tool:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test

  build-tool:
    needs: test-tool
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set Docker tag
        id: set-tag
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "tag=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
          elif [[ "${GITHUB_REF_NAME}" == "refs/heads/main" || "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "tag=latest" >> "$GITHUB_OUTPUT"
          else
            echo "tag=dev" >> "$GITHUB_OUTPUT"
          fi 

      # Enable multi-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: hyperflex/elastic-seamless-upgrade-tool:${{ steps.set-tag.outputs.tag }}
