name: Deploy start script local to gist
run-name: start-script-local deployment

on:
    push:
        branches:
            - main
            - hpf-32-necessary-changes-for-release
    pull_request:
        types: [labeled]
        branches:
            - main
            - develop
    create:

jobs:
    build-frontend:
        if: |
            github.event_name == 'push' ||
            github.event_name == 'pull_request' ||
            (github.event_name == 'create' && github.event.ref_type == 'tag' && startsWith(github.event.ref, 'v'))
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}

            - name: Log in to Docker Hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: Set Docker tag
              id: set-tag
              run: |
                  if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.label.name }}" == "dev" ]]; then
                    echo "tag=dev" >> "$GITHUB_OUTPUT"
                  elif [[ "${{ github.event_name }}" == "create" && "${{ github.event.ref_type }}" == "tag" ]]; then
                    echo "tag=${{ github.event.ref }}" >> "$GITHUB_OUTPUT"
                  else
                    echo "tag=latest" >> "$GITHUB_OUTPUT"
                  fi

            - name: Build and push frontend image
              run: |
                  docker build -t hyperflex/elastic-seamless-upgrade-frontend:${{ steps.set-tag.outputs.tag }} ./frontend
                  docker push hyperflex/elastic-seamless-upgrade-frontend:${{ steps.set-tag.outputs.tag }}

    build-backend:
        if: |
            github.event_name == 'push' ||
            github.event_name == 'pull_request' ||
            (github.event_name == 'create' && github.event.ref_type == 'tag' && startsWith(github.event.ref, 'v'))
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}

            - name: Log in to Docker Hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: Set Docker tag
              id: set-tag
              run: |
                  if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.label.name }}" == "dev" ]]; then
                    echo "tag=dev" >> "$GITHUB_OUTPUT"
                  elif [[ "${{ github.event_name }}" == "create" && "${{ github.event.ref_type }}" == "tag" ]]; then
                    echo "tag=${{ github.event.ref }}" >> "$GITHUB_OUTPUT"
                  else
                    echo "tag=latest" >> "$GITHUB_OUTPUT"
                  fi

            - name: Build and push backend image
              run: |
                  docker build -t hyperflex/elastic-seamless-upgrade-backend:${{ steps.set-tag.outputs.tag }} ./backend
                  docker push hyperflex/elastic-seamless-upgrade-backend:${{ steps.set-tag.outputs.tag }}
